name: Deploy to EKS

on:
  push:

    branches:
      - main  # Adjust the branch according to your setup
env:
  AWS_REGION: us-east-2                   # set this to your preferred AWS region, e.g. us-west-1
  #ECR_REPOSITORY: irfan-task           # set this to your Amazon ECR repository name
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}

      - name: Construct STS Endpoint
        run: |
          echo "Constructed STS Endpoint: sts.${{ secrets.AWS_REGION }}.amazonaws.com"
          nslookup sts.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/ingress.yaml
